Feature/cached octopoes service
minvws/nl-kat-coordination pull request #1204
Opened 2023-06-16 14:15 UTC by Donnype

### Changes
### PLEASE QA THIS PROPERLY, I HAVE SEEN SOME ERRORS DUE TO RABBIT GOING DOWN IN THE LOGS BUT I AM NOT SURE IF THIS WAS DUE TO STARTUP RACE CONDITIONS.

- Cache the octopoes http session and use one rabbitmq connection per celery worker, and one rabbitmq connection for the api (one process).
- Use native support from FastAPI and Celery to spawn connections on startup of the worker/api. 
- Use native support from FastAPI and Celery to close RabbitMQ connections on shutdown of the worker/api. 

Some considerations and issues with the current approach:
- [Pika does not claim that the blocking connections are thread safe](https://pika.readthedocs.io/en/latest/faq.html), but the other services such as the scheduler has not experienced issues with this. For now I have added a `threading.local()` instance to resolve this.
- Running uvicorn with the `--reload` flag means that if we cannot connect to RabbitMQ on application startup (reasonable scenario when we rebuild kat for instance, or when we temporarily kill rabbitmq), the container does not exit. Else the container would kill itself when you code a syntax error during development. But this means that we have to build in retry logic for the initial connection ourselves, so I added RabbitMQ as a dependency that has to be healthy in the docker-compose file. There are still edge cases here where you start octopoes_api with `--no-deps` and RabbitMQ is down. You have to then manually restart Octopoes API since there is no retry logic at the application level implemented. A code change would however be detected by Uvicorn and restart the api successfully in that scenario. We could:
  * Ignore the exception and start the application anyway: then we might see the exception re-appear but at least the application is started so we would stay live and try creating connection until it succeeds [current solution]
  * Build in (longer) retry logic at startup as a lot of Octopoes is not really usable without RabbitMQ
  * (Interesting and ugly thing that I found out also works: if we catch the startup-connection-exceptiond and kill the uvicorn process by doing `os.kill(os.getppid())`, the container actually properly dies and is restarted by docker due to our `restart: unless-stopped` policy! :nerd_face: )

Celery seems to have proper logic to respawn the process when we cannot connect workers on `worker.init`.

### Issue link

Closes https://github.com/minvws/nl-kat-coordination/issues/1162

### Proof

### Celery workers

Celery workers connecting on startup:

![celerycon](https://github.com/minvws/nl-kat-coordination/assets/46660228/d7e77b1a-f2cf-48b3-9d4c-8b6b466d31c9)

Celery workers disconnecting on shutdown:

![celdis](https://github.com/minvws/nl-kat-coordination/assets/46660228/537d4554-3b7a-484a-89dc-56b5cb41a798)

---

### FastAPI

FastAPI connecting on startup:

![rabbitcon](https://github.com/minvws/nl-kat-coordination/assets/46660228/5f686539-f7b2-4850-8363-52fe641024ae)

FastAPI disconnecting on shutdown:

![rabbitclose](https://github.com/minvws/nl-kat-coordination/assets/46660228/ba171fd2-7364-4071-9d0f-04ca90675b13)

FastAPI failing to connect but starting anyways:

![image](https://github.com/minvws/nl-kat-coordination/assets/46660228/427a085f-185e-4beb-9dcf-7cb7d90419d7)

---

### Code Checklist
- [ ] All the commits in this PR are properly PGP-signed and verified;
- [ ] This PR only contains functionality relevant to the issue; tickets have been created for newly discovered issues.
- [ ] I have written unit tests for the changes or fixes I made.
- [ ] For any non-trivial functionality, I have added integration and/or end-to-end tests.
- [ ] I have performed a self-review of my code and refactored it to the best of my abilities.

### Communication
- [ ] I have informed others of any required `.env` changes files if required and changed the `.env-dist` accordingly.
- [ ] I have made corresponding changes to the documentation, if necessary.

---
## Checklist for code reviewers:
Copy-paste the checklist from [the docs/source/templates folder](https://github.com/minvws/nl-kat-coordination/blob/main/docs/source/templates/pull_request_template_review_code.md) into your comment.

---
## Checklist for QA:
Copy-paste the checklist from [the docs/source/templates folder](https://github.com/minvws/nl-kat-coordination/blob/main/docs/source/templates/pull_request_template_review_qa.md) into your comment.

2023-06-23 08:29 UTC, ammar92 approved these changes

2023-06-26 07:53 UTC, Darwinkel commented
## Checklist for QA:
- [x] I have checked out this branch, and successfully ran a fresh `make reset`.
- [x] I confirmed that there are no unintended functional regressions in this branch:
    - [x] I have managed to pass the onboarding flow
    - [x] Objects and Findings are created properly
    - [x] Tasks are created and completed properly
- [x] I confirmed that the PR's advertised `feature` or `hotfix` works as intended.

### What works:
* No apparent regressions
* Restarting containers sequentially one-by-one results in a working deployment

2023-06-26 14:11 UTC, Donnype commented
I added `pytest-timeout` to fix at least the sporadic hanging of the integration test.

2023-06-26 15:29 UTC, dekkers requested changes

2023-06-26 15:29 UTC, dekkers commented on octopoes/octopoes/api/router.py
> +        logger.info("Committed XTDBSession")
The old code also did not commit when an exception happened and I don't think that we want that, so we shouldn't do that inside finally.

2023-06-27 11:56 UTC, Darwinkel commented
Re-tested. Still works fine! :)

2023-06-27 11:58 UTC, dekkers approved these changes

2023-06-27 11:58 UTC, merged