change TOC for usermanual
minvws/nl-kat-coordination pull request #1298
Opened 2023-06-28 11:21 UTC by ring-ring-ring

change the location of the usermanual to the root of the docs TOC + some other changes

2023-06-29 07:37 UTC, ammar92 approved these changes

2023-06-29 08:40 UTC, dekkers requested changes
Most of the images that are moved to manual/img have not been deleted from introduction/img.

2023-07-03 10:14 UTC, ring-ring-ring commented
> Most of the images that are moved to manual/img have not been deleted from introduction/img.

Done - two stay in the same place to allow preview in the webinterface of github. Long story.

2023-07-03 13:03 UTC, Darwinkel approved these changes
Looks good and the images work in the build artifact.

2023-07-04 08:17 UTC, dekkers approved these changes

2023-07-04 11:08 UTC, merged