Enable and upgrade `stylelint` in `pre-commit`
minvws/nl-kat-coordination pull request #1388
Opened 2023-07-13 07:49 UTC by Darwinkel

### Changes
It was planned to integrate `stylelint` as part of the Manon upgrade. The pipeline was implemented, but actually fixing the styling issues has not been done yet. This PR upgrades and enables it.

I'd like to request the frontend-gods @TwistMeister or @HeleenSG to perform the actual fixes :)

Running `pre-commit run --all-files` should already do most of the work.

### Issue link
Originally mentioned in https://github.com/minvws/nl-kat-coordination/pull/548 and https://github.com/minvws/nl-kat-coordination/pull/719.

### Proof
See CI.

---

### Code Checklist
- [ ] All the commits in this PR are properly PGP-signed and verified;
- [ ] This PR only contains functionality relevant to the issue; tickets have been created for newly discovered issues.
- [ ] I have written unit tests for the changes or fixes I made.
- [ ] For any non-trivial functionality, I have added integration and/or end-to-end tests.
- [ ] I have performed a self-review of my code and refactored it to the best of my abilities.

### Communication
- [ ] I have informed others of any required `.env` changes files if required and changed the `.env-dist` accordingly.
- [ ] I have made corresponding changes to the documentation, if necessary.

---
## Checklist for code reviewers:
Copy-paste the checklist from [the docs/source/templates folder](https://github.com/minvws/nl-kat-coordination/blob/main/docs/source/templates/pull_request_template_review_code.md) into your comment.

---
## Checklist for QA:
Copy-paste the checklist from [the docs/source/templates folder](https://github.com/minvws/nl-kat-coordination/blob/main/docs/source/templates/pull_request_template_review_qa.md) into your comment.

2023-07-13 08:23 UTC, ammar92 submitted a review, later dismissed

2023-07-18 13:36 UTC, TwistMeister commented on yarn.lock
Deleted the accidentally added and empty `yarn.lock` file.

2023-07-19 06:40 UTC, Darwinkel commented on boefjes/tests/modules/dummy_boefje_environment_with_pycache/__pycache__/pytest__init__.cpython-311.pyc
Yes. Not sure how this happened.

2023-07-19 06:58 UTC, praseodym approved these changes

2023-07-19 07:36 UTC, praseodym requested changes
## Checklist for QA:
- [x] I have checked out this branch, and successfully ran a fresh `make reset`.
- [x] I confirmed that there are no unintended functional regressions in this branch:
    - [x] I have managed to pass the onboarding flow
    - [x] Objects and Findings are created properly
    - [x] Tasks are created and completed properly
- [ ] I confirmed that the PR's advertised `feature` or `hotfix` works as intended.

### What works:
General functionality excluding styling.

### What doesn't work:
Header is broken:
![Screenshot 2023-07-19 at 09-30-20 OpenKAT - landing_page](https://github.com/minvws/nl-kat-coordination/assets/20283/5462e4e5-a1b9-4084-879b-919ce01de9b6)
![Screenshot 2023-07-19 at 09-31-41 OpenKAT - step_setup_scan_ooi_detail](https://github.com/minvws/nl-kat-coordination/assets/20283/38f106d3-3255-48de-b472-757600329fd2)
Crisis room layout is weird:
![Screenshot 2023-07-19 at 09-34-56 OpenKAT - crisis_room](https://github.com/minvws/nl-kat-coordination/assets/20283/20b1c7cd-ace6-4657-8bf1-fa7c4a074028)
And other styling issues.

### Bug or feature?:
* _bullet point + screenshot (if useful) if it is unclear whether something is a bug or an intended feature._

2023-07-19 08:41 UTC, TwistMeister commented
@praseodym can you verify if this persists when you run `yarn install` and `yarn build` and after that "clear cache and hard reload" the page, with your dev tools open so that we're sure all the correct styles are loaded?

2023-07-19 08:47 UTC, Darwinkel commented
> @praseodym can you verify if this persists when you run `yarn install` and `yarn build` and after that "clear cache and hard reload" the page, with your dev tools open so that we're sure all the correct styles are loaded?
> 
> Edit: When I do this, I see the correct styling for the header. The duplicate submit buttons isn't correct but also isn't regression, since it's been that way for a while now, so I would like to address that in another ticket.

@praseodym and I just verified that the discrepancy is caused by old `dist`/`node_modules` files. Removing those folders and running `make reset` reproduces the below finding:

![image](https://github.com/minvws/nl-kat-coordination/assets/9536436/a73dff9f-f771-43cf-8050-72f4e2cab946)

2023-07-31 14:20 UTC, praseodym commented
Just checked out a clean copy of this branch, the header is still broken.

2023-07-31 14:20 UTC, praseodym requested changes
Just checked out a clean copy of this branch, the header is still broken.

2023-08-07 09:23 UTC, praseodym commented
@HeleenSG JavaScript is indeed still broken, I see the error
`[Error] Failed to load resource: the server responded with a status of 404 () (manon.js, line 0)` in my browser log and the login page looks like this:
![Screenshot 2023-08-07 at 11 22 26](https://github.com/minvws/nl-kat-coordination/assets/20283/2c0b8f1a-84df-4751-b9e0-34040e9a2a63)

2023-08-29 11:40 UTC, ammar92 commented
I have just checked out this branch and can't reproduce any of the errors mentioned here before. I've cleared the Parcel cache and can compile and load `manon.js` from Rocky. Help text and the main menu works as well.

2023-08-29 12:38 UTC, praseodym commented
You probably have some old assets still left over in your Django static directory.

After building 4c481e26 in a completely clean environment, `/static/dist/manon.js` can't be found and the login page looks like this:
![Screenshot 2023-08-29 at 14 35 58](https://github.com/minvws/nl-kat-coordination/assets/20283/c55dea3d-86ab-4670-8cd7-f41946754f88)

2023-08-30 10:03 UTC, ammar92 commented
> You probably have some old assets still left over in your Django static directory.
> 
> After building [4c481e2](https://github.com/minvws/nl-kat-coordination/commit/4c481e2663d68e7c13053b47ee07e280cbbed0f0) in a completely clean environment, `/static/dist/manon.js` can't be found and the login page looks like this: ![Screenshot 2023-08-29 at 14 35 58](https://user-images.githubusercontent.com/20283/264020491-c55dea3d-86ab-4670-8cd7-f41946754f88.png)

You're right, I managed to reproduce this with a freshly checked-out repository. After some debugging and discussion with @HeleenSG we came to the conclusion that `manon.js` wasn't properly linked in `rocky/templates/head.html` after some restructuring of the `assets` directory. It should be fixed now.

2023-08-31 08:58 UTC, underdarknl approved these changes

2023-08-31 09:16 UTC, underdarknl approved these changes

2023-08-31 09:32 UTC, sigio approved these changes

2023-08-31 09:41 UTC, merged