Cleanup templates using ooi detail and list url
minvws/nl-kat-coordination pull request #1681
Opened 2023-08-25 13:01 UTC by ammar92

### Changes
This cleans up some of the `ooi_url` tag usage which makes `href_querystring_from_list.html` and a few partials obsolete.

### Issue link
Closes #1679 

---

### Code Checklist
- [x] All the commits in this PR are properly PGP-signed and verified;
- [ ] This PR only contains functionality relevant to the issue; tickets have been created for newly discovered issues.
- [ ] I have written unit tests for the changes or fixes I made.
- [ ] For any non-trivial functionality, I have added integration and/or end-to-end tests.
- [x] I have performed a self-review of my code and refactored it to the best of my abilities.

### Communication
- [ ] I have informed others of any required `.env` changes files if required and changed the `.env-dist` accordingly.
- [ ] I have made corresponding changes to the documentation, if necessary.

---
## Checklist for code reviewers:
Copy-paste the checklist from [the docs/source/templates folder](https://github.com/minvws/nl-kat-coordination/blob/main/docs/source/templates/pull_request_template_review_code.md) into your comment.

---
## Checklist for QA:
Copy-paste the checklist from [the docs/source/templates folder](https://github.com/minvws/nl-kat-coordination/blob/main/docs/source/templates/pull_request_template_review_qa.md) into your comment.

2023-08-28 08:45 UTC, praseodym approved these changes
lgtm

2023-08-31 10:34 UTC, Rieven requested changes
Linking to Finding detail gives 404. It was KAT-NO-DKIM and Pending severity
<img width="995" alt="image" src="https://github.com/minvws/nl-kat-coordination/assets/30832687/33fc36b6-9fe3-4861-ae13-4252a0c2e669">

2023-08-31 11:42 UTC, ammar92 commented
> Linking to Finding detail gives 404. It was KAT-NO-DKIM and Pending severity
> <img alt="image" width="995" src="https://user-images.githubusercontent.com/30832687/264618074-33fc36b6-9fe3-4861-ae13-4252a0c2e669.png">

Some more context would be appreciated; for example, from what page is the link generated, does this happen with other links from that page, does the object actually exist?

2023-08-31 12:32 UTC, Rieven submitted a review, later dismissed

2023-08-31 13:50 UTC, merged