split output into two raw files, and fix no-output mimetype in main.py
minvws/nl-kat-coordination pull request #2604
Opened 2024-03-05 16:41 UTC by underdarknl

### Changes
The output for the 'no action' situation was invalid, it was a set of single chars, not a set of one item.
The raw files can be split into two with distinct mime-types for each. Not sure about the mimetype of each however.

### Code Checklist
- [ ] All the commits in this PR are properly PGP-signed and verified.
- [ ] This PR only contains functionality relevant to the issue; tickets have been created for newly discovered issues.
- [ ] I have written unit tests for the changes or fixes I made.
- [ ] For any non-trivial functionality, I have added integration and/or end-to-end tests.
- [ ] I have performed a self-review of my code and refactored it to the best of my abilities.

### Communication
- [ ] I have informed others of any required `.env` changes files if required and changed the `.env-dist` accordingly.
- [ ] I have made corresponding changes to the documentation, if necessary.
- [ ] I have included comments in the code to elaborate on what is not self-evident from the code itself, including references to issues and discussions online, or implicit behavior of an interface.

---
## Checklist for code reviewers:
Copy-paste the checklist from [the docs/source/templates folder](https://github.com/minvws/nl-kat-coordination/blob/main/docs/source/templates/pull_request_template_review_code.md) into your comment.

---
## Checklist for QA:
Copy-paste the checklist from [the docs/source/templates folder](https://github.com/minvws/nl-kat-coordination/blob/main/docs/source/templates/pull_request_template_review_qa.md) into your comment.

2024-03-06 12:25 UTC, dekkers commented
Looks good to me, moved to QA.

2024-03-07 12:24 UTC, Donnype requested changes

2024-03-07 12:24 UTC, Donnype commented on boefjes/boefjes/plugins/kat_nmap_ip_range/main.py
> +                ),
```shell
$ python -c 'print(set("info/boefje"))'
{'e', 'f', 'n', 'o', 'i', 'b', 'j', '/'}
```

2024-03-07 13:31 UTC, dekkers commented on boefjes/boefjes/plugins/kat_nmap_ip_range/main.py
> +        ]
```suggestion
        return [{"info/boefje"}, "Skipping range due to unaccepted VSLM.")]
```

2024-03-07 14:33 UTC, ammar92 approved these changes

2024-03-07 14:45 UTC, dekkers approved these changes

2024-03-07 15:20 UTC, merged