Docs: Add nibble documentation
minvws/nl-kat-coordination pull request #3983
Opened 2024-12-19 15:24 UTC by stephanie0x00

### Changes
This PR adds documentation to docs.openkat.nl on what nibbles are and why they replace bits.

### Issue link

Closes #3976

### Demo
n/a

### QA notes
Check if what is written is correct on how nibbles work and if you actually understand what nibbles are now. This is currently still a work in progress while nibbles are further developed. 

---

### Code Checklist

- [x] All the commits in this PR are properly PGP-signed and verified.
- [x] This PR only contains functionality relevant to the issue.
- [ ] I have written unit tests for the changes or fixes I made.
- [x] I have checked the documentation and made changes where necessary.
- [x] I have performed a self-review of my code and refactored it to the best of my abilities.

- [ ] Tickets have been created for newly discovered issues.
- [ ] For any non-trivial functionality, I have added integration and/or end-to-end tests.
- [ ] I have informed others of any required `.env` changes files if required and changed the `.env-dist` accordingly.
- [ ] I have included comments in the code to elaborate on what is not self-evident from the code itself, including references to issues and discussions online, or implicit behavior of an interface.

---

## Checklist for code reviewers:

Copy-paste the checklist from [the docs/source/templates folder](https://github.com/minvws/nl-kat-coordination/blob/main/docs/source/templates/pull_request_template_review_code.md) into your comment.

---

## Checklist for QA:

Copy-paste the checklist from [the docs/source/templates folder](https://github.com/minvws/nl-kat-coordination/blob/main/docs/source/templates/pull_request_template_review_qa.md) into your comment.

2024-12-23 08:45 UTC, originalsouth commented
Great work @stephanie0x00, I made some suggestions to make the work even better :)

2024-12-24 09:02 UTC, ammar92 commented on docs/source/manual/user-manual.rst
> +A more technical explanation on Nibbles can be found at: `https://docs.openkat.nl/developer-documentation/octopoes.html#nibbles <https://docs.openkat.nl/developer-documentation/octopoes.html#nibbles>
Please do not link to external sources, use cross-reference links as documented [here](https://docs.readthedocs.io/en/stable/guides/cross-referencing-with-sphinx.html)

2025-01-08 10:31 UTC, stephanie0x00 commented on docs/source/manual/user-manual.rst
> +A more technical explanation on Nibbles can be found at: `https://docs.openkat.nl/developer-documentation/octopoes.html#nibbles <https://docs.openkat.nl/developer-documentation/octopoes.html#nibbles>
Fixed

2025-01-09 09:40 UTC, originalsouth commented
I changed the target branch to `feature/nibbles`.
If everybody agrees let us merge there.

2025-01-09 09:42 UTC, ammar92 approved these changes

2025-01-09 09:58 UTC, originalsouth requested changes

2025-01-09 10:01 UTC, originalsouth requested changes

2025-01-09 10:01 UTC, originalsouth commented on docs/source/developer-documentation/octopoes.md
> +Nibbles process the data in OpenKAT, they correlate data and try to extract as much information as possible based on the specified rules. Nibbles ensure for a mapping of one or more objects to anothe
```suggestion
Nibbles process the data in OpenKAT, they correlate data and try to extract as much information as possible based on the specified rules. Nibbles ensure for a mapping of one or more objects to another group of objects. Where bits would trigger on objects, Nibbles can trigger on sets of objects. This makes it possible to map a single object to N objects (1-to-N mapping), but also map multiple objects to multiple objects (N-to-M mapping).
```

2025-01-13 07:31 UTC, stephanie0x00 reviewed
review suggestion

2025-01-13 07:40 UTC, merged