Change mula Debian package to always use PostgreSQL
minvws/nl-kat-coordination pull request #597
Opened 2023-03-29 06:21 UTC by dekkers

2023-03-29 07:03 UTC, praseodym requested changes

2023-03-29 07:03 UTC, praseodym commented on docs/source/technical_design/debianinstall.rst
> +For Mukla DB:
Mukla -> Mula

2023-03-29 07:03 UTC, praseodym commented on .github/workflows/test_debian_packages_on_ubuntu.yml
> +      - name: Migrations for Mmula
Mmula -> Mula

2023-03-29 13:53 UTC, praseodym submitted a review, later dismissed

2023-03-29 13:56 UTC, ammar92 submitted a review, later dismissed

2023-03-31 08:10 UTC, underdarknl commented
N.B. this feature should be backported not because of  Z-cert, but because we don't want to have long lingering support for the known broken sqllite combination with sqlalchemy.

2023-04-03 08:09 UTC, merged