Chore/bytes api consistency
minvws/nl-kat-coordination pull request #730
Opened 2023-04-13 14:58 UTC by Donnype

### Changes
This PR fixes several things for Bytes:

Consistency in the API:
-  All object now have a filter endpoint.
- The filter endpoints have an offset
- The raw endpoints make more sense as well

before:
![before](https://user-images.githubusercontent.com/46660228/231786565-2f40fe80-6e25-4934-8037-5a788fe6ba54.png)

after:
![after](https://user-images.githubusercontent.com/46660228/231786599-c2259336-b7f4-4163-b6b3-e42386708f19.png)

I also finally phased out the awkward foreign key from normalizer_meta to boefje_meta. To ensure keeping as much data as possible, I added a data migration that should keep all raw files accessible through the API.

### Issue link
This one also fixes https://github.com/minvws/nl-kat-coordination/issues/707

It relates to https://github.com/minvws/nl-kat-coordination/issues/727.

---
## Checklists for authors:

### Code Checklist
- [x] This PR only contains functionality relevant to the issue; tickets have been created for newly discovered issues.
- [x] I have written unit tests for the changes or fixes I made.
- [x] For any non-trivial functionality, I have added integration and/or end-to-end tests.
- [x] I have performed a self-review of my code and refactored it to the best of my abilities.

### Communication
- [x] I have informed others of any required `.env` changes files if required and changed the `.env-dist` accordingly.
- [x] I have made corresponding changes to the documentation, if necessary.

---
## Checklist for code reviewers:
- [ ] The code does not violate Model-View-Template and our other architectural principles.
- [ ] The code prioritizes readability over performance where appropriate.
- [ ] The code does not bypass authentication or security mechanisms.
- [ ] The code does not introduce any dependency on a library that has not been properly vetted.
- [ ] The code contains docstrings, comments, and documentation where needed.

---
## Checklist for QA:
- [ ] I have checked out this branch, and successfully ran a fresh `make kat`.
- [ ] I confirmed that there are no unintended functional regressions in this branch:
    - [ ] I have managed to pass the onboarding flow
    - [ ] Objects and Findings are created properly
    - [ ] Tasks are created and completed properly
- [ ] I confirmed that the PR's advertised `feature` or `hotfix` works as intended.

### What works:
* _bullet point + screenshot (if useful) per tested functionality_

### What doesn't work:
* _bullet point + screenshot (if useful) per tested functionality_

### Bug or feature?:
* _bullet point + screenshot (if useful) if it is unclear whether something is a bug or an intended feature._

2023-04-20 09:00 UTC, ammar92 submitted a review, later dismissed
Haven't tested this (yet), but looks good in general 👍 

I think the raw endpoints indeed make more sense now.

2023-04-20 10:24 UTC, Darwinkel approved these changes
## Checklist for QA:
- [x] I have checked out this branch, and successfully ran a fresh `make kat`.
- [x] I confirmed that there are no unintended functional regressions in this branch:
    - [x] I have managed to pass the onboarding flow
    - [x] Objects and Findings are created properly
    - [x] Tasks are created and completed properly
- [x] I confirmed that the PR's advertised `feature` or `hotfix` works as intended.

### What works:
* No apparent regressions

2023-04-20 12:43 UTC, Donnype commented on boefjes/boefjes/clients/bytes_client.py
A good cleanup, but it does require some extra QA work (the client is a bit of a blind sport in the boefje test suite)

2023-04-20 12:56 UTC, Donnype commented on bytes/bytes/repositories/meta_repository.py
> +    def has_raw(self, boefje_meta: BoefjeMeta, mime_types: List[MimeType]) -> bool:
This breaks some tests due to sets always trying to hash objects (also see https://github.com/pydantic/pydantic/issues/1090). The `mime_types` field in boefjes/job_models is also not a set, so I'd suggest that if we want to change this everywhere we do it in a separate issue to fix this carefully.

2023-04-21 15:13 UTC, dekkers requested changes

2023-04-24 08:04 UTC, Donnype commented on bytes/bytes/events/events.py
> -class NormalizerMetaReceived(Event):
I checked with JP beforehand and that code was actually already removed

2023-04-24 08:09 UTC, Donnype commented on bytes/bytes/repositories/meta_repository.py
> +        if values.get("organization") or values.get("raw_id"):
Completely overlooked this method, thanks!

2023-04-24 12:35 UTC, Donnype commented on bytes/bytes/repositories/meta_repository.py
> +    def has_raw(self, boefje_meta: BoefjeMeta, mime_types: List[MimeType]) -> bool:
https://github.com/minvws/nl-kat-coordination/issues/796

2023-04-24 15:17 UTC, dekkers approved these changes

2023-04-25 09:56 UTC, dekkers approved these changes

2023-04-25 09:56 UTC, merged