Create boefjes.md
minvws/nl-kat-coordination pull request #828
Opened 2023-04-28 12:30 UTC by ring-ring-ring

### Changes
Moving all content from the readmes to dev docs

2023-05-01 14:52 UTC, dekkers commented
I think the READMEs in each individual directory is not really useful and we can just delete them?

2023-05-09 14:19 UTC, dekkers commented
> > 
> 
> There is some content left in these readmes. The idea of moving them here is to make everything available in one place and start updating as needed.

I don't mean the content that is moved to the documentation, but the README.rst that are added in each directory telling you to go to docs.openkat.nl, isn't having that in the toplevel directory enough?

2023-05-10 07:26 UTC, ring-ring-ring commented
> > > 
> > 
> > 
> > There is some content left in these readmes. The idea of moving them here is to make everything available in one place and start updating as needed.
> 
> I don't mean the content that is moved to the documentation, but the README.rst that are added in each directory telling you to go to docs.openkat.nl, isn't having that in the toplevel directory enough?

Yes it might be enough, we can leave them out. Thanks for clarifying, I misunderstood.

2023-05-10 07:56 UTC, ammar92 approved these changes

2023-05-10 09:54 UTC, Donnype requested changes

2023-05-10 09:54 UTC, Donnype commented on docs/source/developer_documentation/rocky.md
> +## KATalogus View Structure
Since I moved these diagrams in another PR as well, there is a duplicate for the Katalogus views diagram now (see below)!

2023-05-17 12:47 UTC, Donnype approved these changes

2023-05-17 13:14 UTC, dekkers approved these changes

2023-05-17 13:14 UTC, merged