Feature/new permissions
minvws/nl-kat-coordination pull request #950
Opened 2023-05-10 12:12 UTC by Rieven

### Changes
New permissions needed that came out this issue.

### Issue link
Fixes https://github.com/minvws/nl-kat-coordination/issues/916

---

### Code Checklist
- [ ] All the commits in this PR are properly PGP-signed and verified;
- [ ] This PR only contains functionality relevant to the issue; tickets have been created for newly discovered issues.
- [ ] I have written unit tests for the changes or fixes I made.
- [ ] For any non-trivial functionality, I have added integration and/or end-to-end tests.
- [ ] I have performed a self-review of my code and refactored it to the best of my abilities.

### Communication
- [ ] I have informed others of any required `.env` changes files if required and changed the `.env-dist` accordingly.
- [ ] I have made corresponding changes to the documentation, if necessary.

---
## Checklist for code reviewers:
Copy-paste the checklist from [the docs/source/templates folder](https://github.com/minvws/nl-kat-coordination/blob/main/docs/source/templates/pull_request_template_review_code.md) into your comment.

---
## Checklist for QA:
Copy-paste the checklist from [the docs/source/templates folder](https://github.com/minvws/nl-kat-coordination/blob/main/docs/source/templates/pull_request_template_review_qa.md) into your comment.

2023-05-17 11:58 UTC, ammar92 approved these changes
No remarks. Good use of parametrization.

2023-05-17 12:00 UTC, Donnype commented on rocky/tools/models.py
> +            ("can_set_katalogus_settings", "Can set KAT-alogus settings"),
I believe we do not check if someone who has `can_view_katalogus_settings` but not `can_set_katalogus_settings` can see but not set Settings. We only test having both or neither.

2023-05-17 15:38 UTC, praseodym commented on rocky/tests/katalogus/test_katalogus.py
> +    assertContains(response, "You don't have permission to enable boefje")
Done!

2023-05-18 11:18 UTC, Donnype commented on rocky/tools/models.py
> +            ("can_set_katalogus_settings", "Can set KAT-alogus settings"),
Yeah in that case I also wouldn't fix that at this point

2023-05-18 11:20 UTC, Donnype requested changes
Still see my previous comment about the other pluginsettings views!

2023-05-18 13:23 UTC, praseodym commented on rocky/tests/objects/test_objects_findings.py
>  def test_mute_finding_post(
Added

2023-05-18 13:23 UTC, praseodym commented on rocky/tests/katalogus/test_katalogus.py
> +def test_katalogus_clone_settings(redteam_member, organization_b, rf, mocker, mock_models_octopoes):
Added

2023-05-22 15:03 UTC, dekkers commented
Moved to QA

2023-05-23 13:09 UTC, Darwinkel commented
## Checklist for QA:
- [x] I have checked out this branch, and successfully ran a fresh `make reset`.
- [x] I confirmed that there are no unintended functional regressions in this branch:
    - [x] I have managed to pass the onboarding flow
    - [x] Objects and Findings are created properly
    - [x] Tasks are created and completed properly
- [x] I confirmed that the PR's advertised `feature` or `hotfix` works as intended.

### What works:
* User management still works properly
* No apparent regressions

2023-05-23 13:09 UTC, Darwinkel submitted a review, later dismissed

2023-05-24 10:28 UTC, Donnype approved these changes

2023-05-24 13:45 UTC, underdarknl approved these changes

2023-05-24 13:45 UTC, merged